### ISSUE TITLE
Error in loading autobahn/txaio

### ISSUE THREAD

**Issue by MrYsLab** [crossbario/txaio#37] opened 2015-11-15 16:17 UTC
I have a project that requires autobahn in its setup.py. The project is [pymata-aio](https://github.com/MrYsLab/pymata-aio).

The actual project that the user is trying to pip  load is [s2aio](https://github.com/MrYsLab/s2aio), which requires pymata-aio and in turn, requires autobahn/txaio.

Both pymata-aio and s2aio are available on pypi.

The require statement I am using for pymata-aio is:
`
install_requires=['pyserial>=2.7', 'autobahn[asyncio]>=0.10.4'],
`

Both projects require the use of Python 3.5

I have a user who is trying to load on Windows 7  32 bit and is getting this error:

```
Collecting txaio>=1.1.0 (from autobahn[asyncio]>=0.10.4->pymata-aio>=2.7->s2aio)

  Downloading txaio-2.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\temp\pip-build-nbvbbr9i\txaio\setup.py", line 40, in <module>
        with open('README.rst') as f:
    OSError: [Errno 22] Invalid argument: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\temp\pip-build-nbvbbr9i\txaio
```

I am able to load on Windows 10 64 bit and do not see this error. 

Any thoughts on what might be going on and how to resolve this?

Thanks

**Comment by MrYsLab** [comment] 2015-11-16 11:58
Version 2.04 of txaio on pypi has an empty file for README.rst and that is causing the failure. Please correct this.

**Comment by meejah** [comment] 2015-11-16 17:44
It's actually not an empty file, but a link to ``docs/index.rst`` -- perhaps Windows doesn't deal with this properly? What is decompressing the tarball on Windows7 vs 10?

**Comment by MrYsLab** [comment] 2015-11-16 18:08
My user is running Windows 7 32 bit. I run linux and Windows 10  without issue, and do not know the details of win 7. My project is pymata-aio and I have about 2000 downloads per month. I really want to continue using autobahn, so I would appreciate it if an actual file could be used instead  of the link. Thanks.

On November 16, 2015, at 12:44 PM, meejah <notifications@github.com> wrote:

It's actually not an empty file, but a link to docs/index.rst -- perhaps Windows doesn't deal with this properly? What is decompressing the tarball on Windows7 vs 10?

**Comment by oberstet** [comment] 2015-11-16 19:30
@MrYsLab what version of pip? what python version? as @meejah hints, most likely an issue originating from whatever unpacks the archive, since the archive has it:

```console
oberstet@thinkpad-t430s:~/tmp$ wget https://pypi.python.org/packages/source/t/txaio/txaio-2.0.4.tar.gz#md5=8049f08ae608b98f4d9c60f0c9ddf621
--2015-11-16 20:29:42--  https://pypi.python.org/packages/source/t/txaio/txaio-2.0.4.tar.gz
Auflösen des Hostnamen »pypi.python.org (pypi.python.org)«... 185.31.17.223
Verbindungsaufbau zu pypi.python.org (pypi.python.org)|185.31.17.223|:443... verbunden.
HTTP-Anforderung gesendet, warte auf Antwort... 200 OK
Länge: 31780 (31K) [application/octet-stream]
In »»txaio-2.0.4.tar.gz«« speichern.

100%[==================================================================================================================================>] 31.780      --.-K/s   in 0,07s   

2015-11-16 20:29:43 (443 KB/s) - »»txaio-2.0.4.tar.gz«« gespeichert [31780/31780]

oberstet@thinkpad-t430s:~/tmp$ tar -tvf txaio-2.0.4.tar.gz 
drwxrwxr-x oberstet/oberstet 0 2015-10-12 21:38 txaio-2.0.4/
drwxrwxr-x oberstet/oberstet 0 2015-10-12 21:38 txaio-2.0.4/txaio.egg-info/
-rw-rw-r-- oberstet/oberstet 661 2015-10-12 21:38 txaio-2.0.4/txaio.egg-info/SOURCES.txt
-rw-rw-r-- oberstet/oberstet   1 2015-10-12 21:38 txaio-2.0.4/txaio.egg-info/dependency_links.txt
-rw-rw-r-- oberstet/oberstet   6 2015-10-12 21:38 txaio-2.0.4/txaio.egg-info/top_level.txt
-rw-rw-r-- oberstet/oberstet 237 2015-10-12 21:38 txaio-2.0.4/txaio.egg-info/requires.txt
-rw-rw-r-- oberstet/oberstet 4529 2015-10-12 21:38 txaio-2.0.4/txaio.egg-info/PKG-INFO
-rw-rw-r-- oberstet/oberstet    1 2015-10-12 21:38 txaio-2.0.4/txaio.egg-info/not-zip-safe
drwxrwxr-x oberstet/oberstet    0 2015-10-12 21:38 txaio-2.0.4/examples/
-rw-rw-r-- oberstet/oberstet 2164 2015-08-13 21:14 txaio-2.0.4/examples/basic.py
drwxrwxr-x oberstet/oberstet    0 2015-10-12 21:38 txaio-2.0.4/docs/
-rw-rw-r-- oberstet/oberstet 11206 2015-09-27 08:54 txaio-2.0.4/docs/conf.py
-rw-rw-r-- oberstet/oberstet  3159 2015-10-12 21:23 txaio-2.0.4/docs/index.rst
-rw-rw-r-- oberstet/oberstet  7007 2015-09-27 08:54 txaio-2.0.4/docs/api.rst
-rw-rw-r-- oberstet/oberstet   120 2015-09-27 08:54 txaio-2.0.4/docs/contents.rst
-rw-rw-r-- oberstet/oberstet  6001 2015-09-27 08:54 txaio-2.0.4/docs/overview.rst
-rw-rw-r-- oberstet/oberstet  7405 2015-09-27 08:54 txaio-2.0.4/docs/Makefile
-rw-rw-r-- oberstet/oberstet  3741 2015-10-12 21:24 txaio-2.0.4/setup.py
-rw-rw-r-- oberstet/oberstet   190 2015-10-08 18:56 txaio-2.0.4/MANIFEST.in
-rw-rw-r-- oberstet/oberstet  1091 2015-09-27 08:54 txaio-2.0.4/tox.ini
drwxrwxr-x oberstet/oberstet     0 2015-10-12 21:38 txaio-2.0.4/txaio/
-rw-rw-r-- oberstet/oberstet    23 2015-10-12 21:37 txaio-2.0.4/txaio/_version.py
-rw-rw-r-- oberstet/oberstet  4517 2015-09-27 08:54 txaio-2.0.4/txaio/interfaces.py
-rw-rw-r-- oberstet/oberstet  4539 2015-09-21 20:50 txaio-2.0.4/txaio/__init__.py
-rw-rw-r-- oberstet/oberstet 10612 2015-09-27 08:54 txaio-2.0.4/txaio/aio.py
-rw-rw-r-- oberstet/oberstet  2653 2015-09-27 08:54 txaio-2.0.4/txaio/_iotype.py
-rw-rw-r-- oberstet/oberstet  2018 2015-08-13 21:14 txaio-2.0.4/txaio/testutil.py
-rw-rw-r-- oberstet/oberstet 13268 2015-09-27 08:54 txaio-2.0.4/txaio/tx.py
drwxrwxr-x oberstet/oberstet     0 2015-10-12 21:38 txaio-2.0.4/test/
-rw-rw-r-- oberstet/oberstet  5095 2015-09-13 19:54 txaio-2.0.4/test/test_errback.py
-rw-rw-r-- oberstet/oberstet   584 2015-09-27 08:54 txaio-2.0.4/test/test_create.py
-rw-rw-r-- oberstet/oberstet   977 2015-08-13 21:14 txaio-2.0.4/test/util.py
-rw-rw-r-- oberstet/oberstet  3020 2015-08-13 21:14 txaio-2.0.4/test/test_call_later.py
-rw-rw-r-- oberstet/oberstet  1867 2015-10-08 18:56 txaio-2.0.4/test/test_packaging.py
-rw-rw-r-- oberstet/oberstet  3130 2015-08-13 21:14 txaio-2.0.4/test/test_gather.py
-rw-rw-r-- oberstet/oberstet   959 2015-09-16 19:10 txaio-2.0.4/test/test_imports.py
-rw-rw-r-- oberstet/oberstet  4453 2015-09-09 22:10 txaio-2.0.4/test/test_as_future.py
-rw-rw-r-- oberstet/oberstet  7224 2015-09-27 08:54 txaio-2.0.4/test/test_logging.py
-rw-rw-r-- oberstet/oberstet  2669 2015-09-09 22:10 txaio-2.0.4/test/test_callback.py
-rw-rw-r-- oberstet/oberstet  4529 2015-10-12 21:38 txaio-2.0.4/PKG-INFO
-rw-rw-r-- oberstet/oberstet  1160 2015-09-27 08:54 txaio-2.0.4/Makefile
lrwxrwxrwx oberstet/oberstet     0 2015-09-27 08:54 txaio-2.0.4/README.rst -> docs/index.rst
-rw-rw-r-- oberstet/oberstet  1074 2015-08-13 21:14 txaio-2.0.4/LICENSE
-rw-rw-r-- oberstet/oberstet    59 2015-10-12 21:38 txaio-2.0.4/setup.cfg
oberstet@thinkpad-t430s:~/tmp$ 
```

**Comment by oberstet** [comment] 2015-11-16 19:33
this might be the cause: https://github.com/pypa/pip/issues/288 This was landed in pip 1.1

**Comment by MrYsLab** [comment] 2015-11-16 19:37
Python 3.5 and whatever pip is installed with it.

**Comment by oberstet** [comment] 2015-11-16 19:44
mmh, ok. without being able to reproduce for myself, I'd say: maybe a Py 3.5/pip/win32 bug.

**Comment by oberstet** [comment] 2015-11-16 19:47
@meejah not sure .. silly, but could we have README.rst as a regular file, and docs/index.rst an symbolic link instead? maybe this would work around this issue ..

**Comment by meejah** [comment] 2015-11-16 20:00
Hmm, yeah if that works around it that's fine too!

We *could* just have a separate README, too, but it seems silly do duplicate things :/

**Comment by meejah** [comment] 2015-11-16 20:01
@MrYsLab Would you be able to test if making README.rst a "real" file works around you issue?

**Comment by MrYsLab** [comment] 2015-11-16 23:02
Thanks guys for looking into this.  I can send anything you provide for testing to my user, since I too can't test here. Thanks again.

**Comment by MrYsLab** [comment] 2015-11-17 16:37
Just to provide some additional information, I checked with my user and the version of PIP he is using is 7.1.2 which was loaded with Python 3.5. Again, this is Windows 7 32 bit.

**Comment by oberstet** [comment] 2015-11-17 16:43
@meejah maybe we could just try the thing with swapping symling/real file, plus fix #31 and #35, and push a new release? hopefully, this fixes things for @MrYsLab 's user then magically .. if not, we get more feedback.

**Comment by meejah** [comment] 2015-11-17 16:46
@oberstet okay, I can do that today.
I will also take a stab at reproducing first with a Windows7 VM from modern.ie

**Comment by oberstet** [comment] 2015-11-17 16:50
@meejah rgd reproducing .. if you need/want the VM anyway, then sure. otherwise, pls don't waste time on that: let the user do the testing;) there are a couple of issues in AB Py stacking .. which are clear bugs .. the Py3 fallouts etc

**Comment by meejah** [comment] 2015-11-18 04:36
@MrYsLab I have pushed a branch swapping these around and making ``README.rst`` a "real" file; can you have your user try, in a fresh virtualenv (or however they're installing):  ``pip install https://github.com/meejah/txaio/archive/issue37-readme-is-a-link.zip`` before trying ``pip install autobahn`` (and/or your package).

**Comment by MrYsLab** [comment] 2015-11-18 11:49
Thanks so much. I will send this to my user and get back to you ASAP with the results.

**Comment by MrYsLab** [comment] 2015-11-18 14:01
It fixed the problem! I can't thank you enough for your efforts.

**Comment by meejah** [comment] 2015-11-18 16:13
Great, thanks for testing!

@oberstet should be mergable

**Comment by oberstet** [comment] 2015-11-18 17:59
Will merge all PRs later and push a release. What version number should we use?

Am 18.11.2015 5:13 nachm. schrieb meejah <notifications@github.com>:

Great, thanks for testing!

@oberstet<https://github.com/oberstet> should be mergable

**Comment by meejah** [comment] 2015-11-18 18:52
This does add a new (but minor) feature (``is_future()``) but is backwards-compat. So probably ``2.1.0`` if we follow semver.org's recommendations?

**Comment by oberstet** [comment] 2015-11-18 20:23
@meejah @MrYsLab just pushed https://pypi.python.org/pypi/txaio/2.1.0

**Closed by oberstet** 2015-11-18 20:23 UTC
