### ISSUE TITLE
Issue when running with Crossbar 17.3.1 and Python 3.6.1

### ISSUE THREAD

**Issue by lelit** [crossbario/txaio#96] opened 2017-04-01 12:42 UTC
Trying the latest CB release, my test suite raises the following exception:
```
ERROR:root:While firing onDisconnect: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/txaio/aio.py", line 389, in done
    f._result = x
AttributeError: attribute '_result' of '_asyncio.Future' objects is not writable
```

I think this is caused by the fact that starting with Python 3.6.1 `asyncio.Future` is written in C, and thus it's not anymore possible to alter/create new arbitrary attributes.

**Comment by rszalski** [comment] 2017-04-23 09:52
I have the same issue. I don't think Python version is the culprit here.

I've used `pyenv` to install Python `3.6.0`, `3.6.0-debug` and `3.6.1-debug`. On all of those, when I upgraded `autobahn` from `0.17.2` to `0.18.2` I've ran into above mentioned error.

I've also tested `txaio` versions `2.6.1` and `2.7.0` (with both versions of `autobahn`) and they don't seem to make a difference.

Tested on macOS Sierra (10.12.4), 13" Retina MBP Early 2015.

**Comment by meejah** [comment] 2017-04-23 21:19
At some point Python moved to "even more stuff is in C" which appears to include the `_result` attribute. Perhaps it was always in C? But in any case, this attribute is no longer writable and is a "private" thing. So there's nothing else to do but remove the hack in txaio that makes `Future`s look a little bit more like `Deferred`.

There's already warnings in the documentation to not depend on Deferred-style "mutate the result" chaining. Now, you really can't because they'll behave differently in `asyncio` vs `twisted`.

We should also file an Autobahn ticket to audit for anywhere we might depend on Deferred-style chaining, but I do not believe we do.

**Comment by agronholm** [comment] 2017-05-02 09:44
I was hit by this today too.

**Comment by agronholm** [comment] 2017-05-04 17:19
This is indeed caused by autobahn: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/protocol.py#L337
The above line returns a `Future`, and since a `Future` is not `None`, txaio tries to put it in `f._result`, causing this very issue.

**Comment by oberstet** [comment] 2017-05-09 16:25
fixed via https://github.com/crossbario/txaio/pull/104

**Closed by oberstet** 2017-05-09 16:25 UTC
Labels: needs investigation
